[package]
name = "RustSpeedTest"
version = "0.1.0"
authors = ["Artur <von18383@spengergasse.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.18.5"
byte_array = "0.1"
